services:

  api:
    build:
      context: ./api
    container_name: api_platform
    ports:
      - "8000:8000"
    volumes:
      - ./api:/var/www/html
    environment:
      DATABASE_URL: postgres://user:password@db:5432/todolist
    depends_on:
      - db
    command: php -S 0.0.0.0:8000 -t public
    networks:
      - symfony_net

  test:
    build:
      context: ./api
    container_name: phpunit_tests
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:password@db:5432/todolist_test
    volumes:
      - ./api:/var/www/html
    env_file:
      - ./api/.env
      - ./api/.env.test
    networks:
      - symfony_net
    command: >
      sh -c "
      php bin/console doctrine:database:drop --force --if-exists --env=test &&
      php bin/console doctrine:database:create --if-not-exists --env=test &&
      php bin/console doctrine:migrations:migrate --no-interaction --env=test &&
      vendor/bin/phpunit
      "

  front:
    build:
      context: ./front
    container_name: frontend
    ports:
      - "3001:3000"
    volumes:
      - ./front:/usr/src/app
    stdin_open: true
    tty: true

  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: todolist
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - symfony_net
  mailer:
    image: axllent/mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      symfony_net:
       aliases:
          - todolist-mailer-1

networks:
  symfony_net:
    driver: bridge

volumes:
  db_data:
