name: CI

on:
  push:
    branches:
      - main
      - feature/tests  # Assurez-vous que la branche est incluse
  pull_request:
    branches:
      - main
      - feature/tests  # Assurez-vous que la branche est incluse

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: todolist_test
        ports:
          - 5433:5433

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Start application
        run: docker-compose up -d

      - name: Install dependencies
        run: docker exec -T api_platform composer install

      - name: Run PHPUnit tests
        run: docker-compose run --rm test
