name: CI

on:
  push:
    branches:
      - main
      - feature/tests  # Assurez-vous que la branche est incluse
  pull_request:
    branches:
      - main
      - feature/tests  # Assurez-vous que la branche est incluse

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      APP_ENV: test
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      APP_SECRET: ${{ secrets.APP_SECRET }}
      JWT_PASSPHRASE: ${{ secrets.JWT_PASSPHRASE }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Start application
        run: docker-compose up -d

      - name: Install dependencies
        run: docker exec api_platform composer install

      - name: Run PHPUnit tests
        run: docker-compose run --rm test

      - name: List files in current directory
        run: ls -l